#ifndef MAIN_LORA_ENCRYPTER_SECRET_H_
#define MAIN_LORA_DECRYPTER_SECRET_H_

#define ENCRYPTER_SEND_SECRET_KEY_SIZE 3
const uint8_t ENCRYPTER_SEND_SECRET_KEY[3] = { 0x01, 0x02, 0x03 };

#endif /* MAIN_LORA_ENCRYPTER_SECRET_H_ */
