#ifndef MAIN_LORA_ENCRYPTER_SECRET_H_
#define MAIN_LORA_DECRYPTER_SECRET_H_

// REPLACE BEFORE BUILD FINISH FIRMWARE!

#define ENCRYPTER_SEND_SECRET_KEY_SIZE 3
#define ENCRYPTER_SEND_SECRET_KEY { 0x01, 0x02, 0x03 }

#define LORA_ADDRESS              0x1234
#define LORA_SECRET               0x5678
#define LORA_ENABLE_CONFIRURE     false

#endif /* MAIN_LORA_ENCRYPTER_SECRET_H_ */
